FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Deportes UNQ

Polls is a simple API allowing consumers to view polls and vote in them.

## Competitions Collection [/competitions]

### List All Competitions [GET]

+ Response 200 (application/json)

        [
            {
                "id": 0,
                "name": "Liga",
                "year": 2019,
                "champion": "Universidad Nacional de Quilmes",
                "logo_url": "Unqui-2019"
            },
            {
                "id": 1,
                "name": "Liga",
                "year": 2019,
                "champion": "Universidad Nacional de Quilmes",
                "logo_url": "Unqui-2019"
            },
            {
                "id": 2,
                "name": "Liga",
                "year": 2019,
                "champion": "Universidad Nacional de Quilmes",
                "logo_url": "Unqui-2019"
            },
            {
                "id": 3,
                "name": "Liga",
                "year": 2019,
                "champion": "Universidad Nacional de Quilmes",
                "logo_url": "Unqui-2019"
            },
            {
                "id": 4,
                "name": "Liga",
                "year": 2019,
                "champion": "Universidad Nacional de Quilmes",
                "logo_url": "Unqui-2019"
            },
            {
                "id": 5,
                "name": "Liga",
                "year": 2019,
                "champion": "Universidad Nacional de Quilmes",
                "logo_url": "Unqui-2019"
            },
            {
                "id": 6,
                "name": "Liga",
                "year": 2019,
                "champion": "Universidad Nacional de Quilmes",
                "logo_url": "Unqui-2019"
            },
            {
                "id": 7,
                "name": "Liga",
                "year": 2019,
                "champion": "Universidad Nacional de Quilmes",
                "logo_url": "Unqui-2019"
            }
        ]